common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pybo import views
from rest_framework import routers
from pybo.views import MovieViewSet
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter() 
router.register('movies',MovieViewSet) # prefix = movies , viewset = MovieViewSet

urlpatterns = [
    path("pybo/", include('pybo.urls')),
    #path('pybo/', include('allauth.urls')),
    path('pybo/',include('django.contrib.auth.urls')),
    #path('accounts/',include('django.contrib.auth.urls')),
    #path('accounts/',include('allauth.urls')),
    #re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/',include(router.urls)),
    path("admin/", admin.site.urls),
    
    path('common/', include('common.urls')),
    path('', views.main, name='main'),  # '/' 에 해당되는 path
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
<link rel="stylesheet" href="../sass/login.css">


{% extends "base.html" %}
{% block content %}


<!--https://d3j8buaepzkvqi.cloudfront.net/mp4/Video_Preview.mp4-->

<div class="container-fluid main-container">

    
    
    <video id="background_video1" style="width: 100%; height: 100vh; object-fit: cover; position: fixed; top: 0px; left: 0px; z-index: -1; user-select: auto;" muted="muted" poster="" playsinline="" autoplay="autoplay"  preload="auto">
        <source src="https://vod-progressive.akamaized.net/exp=1675198555~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F232%2F18%2F451164052%2F1984878240.mp4~hmac=2aa2d00754102b2f8ac275cdcf9fe9c8b9fb2a78a73036c2af00d017fbff6fa5/vimeo-prod-skyfire-std-us/01/232/18/451164052/1984878240.mp4"  type="video/mp4" style="user-select: auto;" >
        <source src="https://vod-progressive.akamaized.net/exp=1675198450~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F2593%2F22%2F562965796%2F2661999829.mp4~hmac=ce05004eb0a53a18c733e361738d06174f4cf54c3b6e71212e01fefb18bddbb5/vimeo-prod-skyfire-std-us/01/2593/22/562965796/2661999829.mp4"  type="video/mp4" style="user-select: auto;" >
        <source src="https://vod-progressive.akamaized.net/exp=1675198589~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F2600%2F22%2F563001938%2F2662171255.mp4~hmac=0922ddacd1726b44294ec87441a4099963e0d68b1766ea27a323db8973ccf1e7/vimeo-prod-skyfire-std-us/01/2600/22/563001938/2662171255.mp4"  type="video/mp4" style="user-select: auto;" >
    </video>
   


    <div class="container" id="wc-container" style="user-select: auto;">

        <div class="row mobile-only" style="user-select: auto;">
            <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
                <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
            </div>
        </div>

        <div class="row" id="main_row" style="user-select: auto;">


            <!-- <div class="col-md-6 pc-only" style="text-align: left; margin-bottom: 0px; padding-left: 0px;"> -->

            <!-- <img class="featurette-image img-fluid mx-auto" id="main_image_1" src="https://d3j8buaepzkvqi.cloudfront.net/img/treatment.gif"alt=""> -->
            <!-- <video style="width: 100%; margin-top: 24px;" muted="" poster="https://d3j8buaepzkvqi.cloudfront.net/img/main-02_resized.png" playsinline="" autoplay="" loop="" preload="auto">
                <source src="https://d3j8buaepzkvqi.cloudfront.net/mp4/0304_main.mp4" type="video/mp4">
            </video> -->
            <!-- </div> -->

            <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

                <div id="main_heading" style="padding-left: 10px;padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                    <div class="row" style="padding-top: 2rem; user-select: auto;">
                        <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                            <h3 class="pc-only"  style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>
                            <h3 class="feature-heading mb-5 pc-only heading_mention" style="user-select: auto;">디지털 알렉산더의 모험</h3>
                            <h3 class="feature-heading mb-3 mobile-only" style="user-select: auto;">로그인</h3>
                        </div>
                        <div class="col-md-12" style="user-select: auto;"></div>
                    </div>




                    <div style="user-select: auto;">

                        <!-- <hr> -->

                        <div class="row" style="text-align: center; user-select: auto; " >
                            <div class="col-md-12" style="user-select: auto;">
                                <!-- <h3 class="feature-heading">로그인</h3> -->
                            </div>
                            <!-- <div class="col-md-8 offset-md-2" style="padding-left: 15px; padding-right: 15px;"> -->
                            <div class="col-md-12" style="padding-left: 15px; padding-right: 15px; user-select: auto;">
                                <form method="post" action="{% url 'common:login' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->

                                    {% include "form_errors.html" %}
                                    <div class="mb-3">
                                        <label for="username">사용자ID</label>
                                        <input type="text" class="form-control" name="username" id="username"
                                               value="{{ form.username.value|default_if_none:'' }}">
                                    </div>
                                    <div class="mb-3">
                                        <label for="password">비밀번호</label>
                                        <input type="password" class="form-control" name="password" id="password"
                                               value="{{ form.password.value|default_if_none:'' }}">
                                    </div>
                                    <button type="submit" class="btn btn-primary">로그인</button>
                                </form>
<!--                                <form method="POST" id="login_submit_form" style="user-select: auto;">-->
<!--                                    <input type="hidden" name="csrfmiddlewaretoken" value="WcFuNSPa74NdWQZHycsmlTgYxq7Yq5KF5ZxQ4xiSsKX08UMLxfIN75jkuocXaqFR" style="user-select: auto;">-->


<!--                                    <div id="div_id_email" class="form-group" style="user-select: auto;">-->
<!--                                        <label for="id_email" class="control-label  requiredField" style="user-select: auto;">-->
<!--                                        이메일<span class="asteriskField" style="user-select: auto;">*</span>-->
<!--                                        </label>-->

<!--                                        <div class="controls " style="user-select: auto;">-->
<!--                                        <input type="text" name="email" autofocus="" autocapitalize="off" class="textinput textInput form-control" required="" id="id_email" style="user-select: auto;">-->
<!--                                        </div>-->
<!--                                    </div>-->

<!--                                    <div id="div_id_password" class="form-group" style="user-select: auto;">-->
<!--                                        <label for="id_password" class="control-label  requiredField" style="user-select: auto;">-->
<!--                                        비밀번호<span class="asteriskField" style="user-select: auto;">*</span>-->
<!--                                        </label> <div class="controls " style="user-select: auto;">-->
<!--                                        <input type="password" name="password" class="textinput textInput form-control" required="" id="id_password" style="user-select: auto;">-->
<!--                                    </div>-->
<!--                                    </div>-->

<!--                                    <input type="hidden" id="next_url" name="next" value="" style="user-select: auto;">-->
<!--                                    <input type="hidden" id="id_msg_listen" name="msg_listen" value="" style="user-select: auto;">-->
<!--                                    <input type="hidden" id="id_msg_platform" name="msg_platform" value="" style="user-select: auto;">-->
<!--                                    <input type="button" class="btn btn-hover color-3 btn-block" id="login_submit" value="로그인" style="user-select: auto;">-->
<!--                                </form>-->
                                <br style="user-select: auto;">
                                <p style="user-select: auto;"> <a href="https://1021-121-134-166-70.jp.ngrok.io/pybo/password_reset" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                                </p>
                            </div>

                            <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                                <!-- <hr> -->
                                <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요?
                                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                                </p>
                            </div>


                        </div>

                        <hr style="margin-top: 0px; user-select: auto;">

                        <p class="pc-only app_banner" style="justify-content: center; display: flex; user-select: auto;">앱을 다운로드하세요.</p>

                        <div class="row main-buttons app_banner" style="justify-content: center; display: flex; user-select: auto; ">

                            <a class="" href="https://play.google.com/store/apps/details?id=com.assemblecircle.webceph" style=" user-select: auto; ">
                                <img alt="Available on Google Play" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/playstore.png" style="height: 40px; user-select: auto;">
                            </a>
                            <a class="" href="https://apps.apple.com/app/webceph/id1534844081" style="user-select: auto;">
                                <img alt="Available on the App Store" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/appstore.png" style="height: 40px; user-select: auto;">
                            </a>
                        </div>

                        <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
<script>
    document.getElementById('background_video1').play();
</script>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}


<div class="container-fluid main-container" style="padding-left: 0px; padding-right: 0px; padding-bottom: 0px; user-select: auto;">  
  
  <video id="background_video" style="width: 100vw; height: 100vh; object-fit: cover; position: fixed; top: 0px; left: 0px; z-index: -1; user-select: auto;" muted="" poster="" playsinline="" autoplay="" loop="" preload="auto">
      <source src="https://d3j8buaepzkvqi.cloudfront.net/mp4/Video_Preview.mp4" type="video/mp4" style="user-select: auto;">
  </video>

  <div class="container" id="wc-container" style="user-select: auto;">
  <div class="row" id="main_row" style="user-select: auto;">
  
  
  
  
    <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4 card py-5" id="main_heading" style="margin-top: 24px;margin-bottom: 24px;border-radius: 1rem;background-color: rgba(255, 255, 255, 0.87);user-select: auto;">
  
  
                            
  
                <div class="row" style="user-select: auto;">
                    <div class="col-md-12 mb-3 pc-only" style="text-align: center; user-select: auto;">
  
                      <img class="pc-only mt-3" src="https://webceph.s3.amazonaws.com/static/img/LOGO_60.png" style="height: 25px; margin-bottom: 15px; user-select: auto;">
                      <h3 class="feature-heading mb-2 pc-only" style="user-select: auto;">디지털 인공지능 치의학시대로의 도약</h3>
                    </div>
                    <div class="col-md-12" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                          
                <div id="main_formset" style="min-height: 450px; user-select: auto;">
                  
                <!-- multistep form -->

                <form method="post" action="{% url 'common:signup' %}">
             
                  <fieldset id="fieldset_stage_1" style="background: white;
                  border: 0 none;
                  border-radius: 1.0rem;
                  box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.07);
                  padding: 20px 30px;
                  box-sizing: border-box;
                  width: 90%;
                  margin: 0 5%;
                  
                  /*stacking fieldsets above each other*/
                  position: relative;">
                    

                      {% csrf_token %}
                      {% include "form_errors.html" %}

                    <div style="text-align: left; user-select: auto;">

                    <div class="form-row" style="user-select: auto;">
                      <div class="form-group col-6 mb-0" style="width:100%; user-select: auto;">
                        
                        <div id="div_id_first_name" class="form-group" style="user-select: auto;">
                            
                                <label for="id_first_name" class="control-label " style="user-select: auto;">
                                    이름*
                                </label>

                                    <div class="controls " style="user-select: auto;">
                                      <input type="text" class="form-control" name="username" id="username" style="width:100%; user-select: auto;"
                                      value="{{ form.username.value|default_if_none:'' }}">
                                    </div>  
                        </div>
                      </div>
                    </div>
                    
                        <div id="div_id_email" class="form-group" style="user-select: auto;">
                            
                                <label for="id_email" class="control-label  requiredField" style="user-select: auto;">
                                    이메일<span class="asteriskField" style="user-select: auto;">*</span>
                                </label>
            
                                    <div class="controls " style="user-select: auto;">
                                      <input type="text" class="form-control" name="email" id="email"  style="width:100%; user-select: auto;"
                                      value="{{ form.email.value|default_if_none:'' }}">
                                    </div>   
                        </div>
      
  
  
                    <div class="form-row" style="user-select: auto;">
                      <div class="form-group col-6 mb-0" style="width:100%; user-select: auto;">
                        <div id="div_id_password1" class="form-group" style="user-select: auto;">
          
                          <label for="id_password1" class="control-label  requiredField" style="user-select: auto;">
                              비밀번호<span class="asteriskField" style="user-select: auto;">*</span>
                          </label>
        
                          <div class="controls " style="user-select: auto;">
                            <input type="password" class="form-control" name="password1" id="password1"  style="width:100%; user-select: auto;"
                            value="{{ form.password1.value|default_if_none:'' }}">
                          </div>
                        </div>
                      </div>



                    <div class="form-group col-6 mb-0" style="width:100%; user-select: auto;">
                      <div id="div_id_password2" class="form-group" style="user-select: auto;">
          
                      <label for="id_password2" class="control-label  requiredField" style="user-select: auto;">
                          비밀번호 확인<span class="asteriskField" style="user-select: auto;">*</span>
                      </label>
        
                      <div class="controls " style="user-select: auto;">
                        <input type="password" class="form-control" name="password2" id="password2"  style="width:100%; user-select: auto;"
                        value="{{ form.password2.value|default_if_none:'' }}">
                      </div>    
                      </div>
                    </div>
                      
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary" style="width:100%; margin-top:5%; background-image: linear-gradient(to right, #2a31ff, #8705ff,#2a31ff, #8705ff);">생성하기</button>
                  
                  </fieldset>
                </form>
                  
                </div>
  
                    <p class="pc-only app_banner" style="justify-content: center; display: flex; user-select: auto;">앱을 다운로드하세요.</p>
  
                    <div class="row main-buttons app_banner" style=" width:100%; text-align:center; display: flex; user-select: auto;">
                      
                        <a class="" href="https://play.google.com/store/apps/details?id=com.assemblecircle.webceph" style="margin-right: 8px; user-select: auto;">
                          <img alt="Available on Google Play" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/playstore.png" style="height: 40px; user-select: auto;">
                        </a>
                        <a class="" href="https://apps.apple.com/app/webceph/id1534844081" style="margin-top:3%; user-select: auto;">
                          <img alt="Available on the App Store" class="Rt8TI " src="https://d3j8buaepzkvqi.cloudfront.net/img/appstore.png" style="height: 40px; user-select: auto;">
                        </a>
                    </div> 
 
                    <p class="company-copyright" style="text-align: center; margin-top: 40px; user-select: auto;">(주)어셈블써클 © 2022 </p>

                    </div>
                </div>
        
  
  
  
    </div>
  
  </div>
  
              
                       
  
  </div>
  

  
  </div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
{% load static %}
<link rel="stylesheet" type="text/css" href="static/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../static/style.css">



<div class="hero">

    <nav>
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>
        <div id="navbarSupportedContent">
            <ul>
                <li>
                    {% if user.is_authenticated %}


                    <img src="{%static 'img/user.png' %}" onclick="toggleMenu()" class="user-pic" width="118px" />

                    <div class="sub-menu-wrap" id="subMenu">
                        <div class="sub-menu">

                            <div class="user-info">
                                <img src="{%static 'img/user.png' %}">
                                <h3>{{ user.username }}</h3>
                            </div>

                            <hr>

                            <a href="#" class="sub-menu-link">
                                <img src="{%static 'img/profile.png' %}">
                                <p>edit profile</p>
                                <span>></span>
                            </a>
                            <a href="{% url 'pybo:user_profile' %}" class="sub-menu-link">
                                <img src="{%static 'img/setting.png' %}">
                                <p>setting profile</p>
                                <span> > </span>
                            </a>
                            <a href="#" class="sub-menu-link">
                                <img src="{%static 'img/help.png' %}">
                                <p>help & surport</p>
                                <span> > </span>
                            </a>
                            <a href="{% url 'common:logout' %}" class="sub-menu-link">
                                <img src="{%static 'img/logout.png' %}">
                                <p>logout</p>
                                <span> > </span>
                            </a>

                        </div>
                    </div>


                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                               <li class="nav-item">
                                   <a class="nav-link" href="{% url 'pybo:index' %}">질문&답변</a>
                               </li>
                               <li class="nav-item">
                                   <a class="nav-link" href="{% url 'pybo:index2' %}">알렉산더 사진</a>
                            </li> 
            </ul>

        </div>
    </nav>
</div>

<script>
    let subMenu = document.getElementById("subMenu");

    function toggleMenu(){
        subMenu.classList.toggle("open-menu");
        console.log("dssddsds");
    }
</script>

templates/password_reset.html
<div class="container" id="wc-container" style="user-select: auto;">

    <div class="row mobile-only" style="user-select: auto;">
        <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
            <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
        </div>
    </div>

    <div class="row" id="main_row" style="user-select: auto;">

        <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

            <div id="main_heading" style="padding-left: 10px;width: 90%; margin-left: 4.5%; padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                <div class="row" style="padding-top: 2rem; user-select: auto;">
                    <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                        <h3 class="pc-only"  style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>

                        <form method="post" action="{% url 'password_reset' %}" style="width: 100%;">
                            <div>
                            {% csrf_token %}
<!--                            {{ form.as_p }}-->
                                <input placeholder="Email" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" style="user-select: auto;
                                        width:40%;background-color: white; height: 5%;margin-bottom: 15px;  ">
                            </div>
                            <button type="submit"
                                    style="cursor: pointer; width: 20%; height: 5%; padding:6px 15px; border-radius: 5px; outline: none; border: none; background: #0F3758; color: white">
                                send Email
                            </button>
                        </form>
                    </div>
                    <div class="col-md-12" style="user-select: auto;"></div>
                </div>
                <div style="user-select: auto;">
                    <div class="row" style="text-align: center; user-select: auto; " >
                        <div class="col-md-12" style="padding-left: 15px;padding-top: 50px; padding-right: 15px; user-select: auto;">
                            <p style="user-select: auto;">
                                <a href="https://e20f-121-134-166-70.jp.ngrok.io/pybo/password_reset/" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                            </p>
                        </div>
                        <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                            <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요?
                                <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                            </p>
                        </div>
                    </div>
                    <hr style="margin-top: 0px; user-select: auto;">
                    <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/password_reset_done_fail.html
<html><head></head><body><div class="container" id="wc-container" style="user-select: auto;">

    <div class="row mobile-only" style="user-select: auto;">
        <div class="col-12" style="text-align: center; margin-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 50px; width: 100%; user-select: auto;">
            <h3 class="feature-heading mb-2 heading_mention pc-only" style="user-select: auto;"></h3>
        </div>
    </div>

    <div class="row" id="main_row" style="user-select: auto;">

        <div class="col-lg-8 offset-lg-2 col-xl-4 offset-xl-4" style="padding: 0px; user-select: auto;">

            <div id="main_heading" style="padding-left: 10px;width: 90%; margin-left: 4.5%; padding-right: 10px;background-color: rgba(255, 255, 255, 0.87);user-select: auto; border-radius: 1rem; box-shadow: 0 0 15px 1px rgb(0 0 0 / 40%); ">

                <div class="row" style="padding-top: 2rem; user-select: auto;">
                    <div class="col-md-12 mb-3" style="text-align: center; user-select: auto;">

                        <h3 class="pc-only" style="height: 25px; margin-bottom: 15px; user-select: auto;">DOG AND CAT</h3>

                        <form method="post" action="/pybo/password_reset/" style="width: 100%;">
                            <div>
                            <input type="hidden" name="csrfmiddlewaretoken" value="7fYKeSJnAACGBBioyOHm9HNfoCPgpfN0j3tSoV0xnXUcLbLw4X9gcljIAy66LTcO">
<!--                            <p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
    
    
      
    
  </p>-->
                                <input placeholder="Email" type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" style="user-select: auto;
                                        width:40%;background-color: white; height: 5%;margin-bottom: 15px;  ">
                            </div>
                            <button type="submit" style="cursor: pointer; width: 20%; height: 5%; padding:6px 15px; border-radius: 5px; outline: none; border: none; background: #0F3758; color: white">
                                send Email
                            </button>
                        </form>
                    </div>
                    <div class="col-md-12" style="user-select: auto;"></div>
                </div>
                
                <div style="user-select: auto;">
                    <div class="row" style="text-align: center; user-select: auto; ">
                        <div class="col-md-12" style="padding-left: 15px; padding-right: 15px; user-select: auto;">
                            <h5 class="email-err" style="height:25px;margin-bottom: 15px;color:red">이메일을 잘못 입력하셨습니다. 다시 입력해주세요.</h5>
                            <p style="user-select: auto;">
                                <a href="https://e20f-121-134-166-70.jp.ngrok.io/pybo/password_reset/" style="user-select: auto;">비밀번호를 잊으셨나요? </a>
                            </p>
                        </div>
                        <div class="col-md-12" id="footer_login" style="padding-left: 0px; padding-right: 0px; user-select: auto;">
                            <p style="margin-top: 8px; user-select: auto;">아직 dog and cat 회원이 아니신가요?
                                <a class="nav-link" href="/common/signup/">회원가입</a>
                            </p>
                        </div>
                    </div>
                    <hr style="margin-top: 0px; user-select: auto;">
                    <p class="company-copyright" style="text-align: center; margin-top: 20px; padding-bottom: 40px; user-select: auto;">AssembleCircle Corporation © 2022 </p>
                </div>
            </div>
        </div>
    </div>
</div>







</body></html>